/*
  # Create General table with proper schema and RLS policies

  1. New Tables
    - `General` table for shipment data with all required columns
    - Proper primary key handling for existing identity column
    - Foreign key relationship to Usuarios table

  2. Security
    - Enable RLS on General table
    - Service role full access policy
    - Users can manage own shipments policy
    - Operators can read all shipments for opportunities

  3. Changes
    - Handle existing identity column for id_Envio
    - Add all missing columns if they don't exist
    - Set up proper RLS policies for multi-role access
*/

-- First, check if the General table exists and handle accordingly
DO $$
BEGIN
  -- If table doesn't exist, create it with identity column
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'General') THEN
    CREATE TABLE "General" (
      "id_Envio" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "id_Usuario" integer NOT NULL,
      "Estado" text DEFAULT 'Solicitado',
      "Origen" text,
      "Destino" text,
      "Distancia" numeric,
      "Tipo_Carga" text,
      "Tipo_Planificacion" text DEFAULT 'Normal',
      "Tipo_Vehiculo" text,
      "Tipo_Envio" text DEFAULT 'Normal',
      "Necesidades_Especiales" text,
      "Operador" text,
      "Fecha_Retiro" timestamptz,
      "Oferta" integer,
      "Peso" text,
      "Dimension_Largo" integer,
      "Dimension_Ancho" integer,
      "Dimension_Alto" integer,
      "Horario_Retiro" time,
      "Observaciones" text,
      "Costos" character varying,
      "Tipo_Carroceria" text,
      "Tiempo_Estimado_Operacion" character varying,
      "Parada_Programada" character varying,
      "Nombre_Dador" text
    );
  ELSE
    -- Table exists, add any missing columns
    -- Add columns that might be missing from the existing table
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'General' AND column_name = 'Tiempo_Estimado_Operacion') THEN
      ALTER TABLE "General" ADD COLUMN "Tiempo_Estimado_Operacion" character varying;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'General' AND column_name = 'Parada_Programada') THEN
      ALTER TABLE "General" ADD COLUMN "Parada_Programada" character varying;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'General' AND column_name = 'Nombre_Dador') THEN
      ALTER TABLE "General" ADD COLUMN "Nombre_Dador" text;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'General' AND column_name = 'Horario_Retiro') THEN
      ALTER TABLE "General" ADD COLUMN "Horario_Retiro" time;
    END IF;
  END IF;
END $$;

-- Add foreign key constraint to Usuarios table if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'General_id_Usuario_fkey' 
    AND table_name = 'General'
  ) THEN
    ALTER TABLE "General" 
    ADD CONSTRAINT "General_id_Usuario_fkey" 
    FOREIGN KEY ("id_Usuario") REFERENCES "Usuarios"("id_Usuario") 
    ON UPDATE CASCADE ON DELETE CASCADE;
  END IF;
END $$;

-- Enable Row Level Security
ALTER TABLE "General" ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid conflicts
DROP POLICY IF EXISTS "Service role full access general" ON "General";
DROP POLICY IF EXISTS "Users can manage own shipments" ON "General";
DROP POLICY IF EXISTS "Users can read all shipments" ON "General";
DROP POLICY IF EXISTS "Users can insert own shipments" ON "General";
DROP POLICY IF EXISTS "Operators can read all shipments" ON "General";

-- Create RLS policies
CREATE POLICY "Service role full access general"
  ON "General"
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Policy for users to manage shipments they own
CREATE POLICY "Users can manage own shipments"
  ON "General"
  FOR ALL
  TO authenticated
  USING (
    "id_Usuario" IN (
      SELECT "Usuarios"."id_Usuario"
      FROM "Usuarios"
      WHERE "Usuarios".auth_user_id = auth.uid()
    )
  )
  WITH CHECK (
    "id_Usuario" IN (
      SELECT "Usuarios"."id_Usuario"
      FROM "Usuarios"
      WHERE "Usuarios".auth_user_id = auth.uid()
    )
  );

-- Additional policy for operators to read all shipments (for opportunity viewing)
CREATE POLICY "Operators can read all shipments"
  ON "General"
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM "Usuarios"
      WHERE "Usuarios".auth_user_id = auth.uid()
      AND ("Usuarios"."Rol_Operativo" LIKE '%operador%' OR "Usuarios"."Rol_Operativo" LIKE '%broker%')
    )
  );